import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import AdminLayout from "@/components/layout/AdminLayout";
  


const geistSans = localFont({
  src: "../../public/assets/fonts/GeistMonoVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../../public/assets/fonts/GeistVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "CAR Rental App : Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <AdminLayout>
        {children}
      </AdminLayout>

      </body>
    </html>
  );
}
